# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HMn5YZ2VVQTf4cmzI440Yr4_BeKNActJ
"""

import os
os.environ["USER_AGENT"] = "hf-space-rag-bot"
os.environ["CUDA_VISIBLE_DEVICES"] = ""


import gradio as gr
from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

# -----------------------------
# LOAD & INDEX PHYSICS DATA
# -----------------------------
from langchain_core.documents import Document


# -----------------------------
# OFFLINE PHYSICS DOCUMENTS
# -----------------------------
docs = [
    Document(page_content="""
String theory proposes that fundamental particles are one-dimensional
vibrating strings rather than point particles. It attempts to unify
quantum mechanics and general relativity and requires extra dimensions.
"""),
    Document(page_content="""
Dark matter is invisible matter that affects galaxies through gravity.
Dark energy causes the accelerated expansion of the universe and
dominates the cosmic energy budget.
"""),
    Document(page_content="""
Time dilation is a relativistic effect where time passes at different
rates due to velocity or gravity, experimentally confirmed by GPS.
"""),
    Document(page_content="""
Stars form from collapsing clouds of gas and dust, eventually igniting
nuclear fusion in their cores.
"""),
]


text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1500,
    chunk_overlap=200
)
splits = text_splitter.split_documents(docs)
if not splits:
    raise ValueError("No documents available for embedding")


embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    model_kwargs={"device": "cpu"}
)

vectorstore = Chroma.from_documents(splits, embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

# -----------------------------
# CORE PHYSICS RAG LOGIC
# -----------------------------
def detailed_physics_app(query: str) -> str:
    docs = retriever.invoke(query)
    context = "\n".join([doc.page_content[:800] for doc in docs])

    q = query.lower()

    if "string" in q:
        answer = """
🧵 **STRING THEORY**

• Fundamental particles are vibrating strings (~10⁻³⁵ m)
• Requires **10 dimensions** (9 space + 1 time)
• Extra dimensions compactified as **Calabi–Yau manifolds**
• 5 consistent theories unified by **M-Theory (11D)**
• Predicts gravity via closed strings
• No experimental confirmation yet
        """

    elif "dark" in q:
        answer = """
🌌 **DARK ENERGY & DARK MATTER**

**Dark Energy (68%)**
• Causes accelerated expansion
• Equation of state: w ≈ −1
• Modeled via ΛCDM

**Dark Matter (27%)**
• Explains galaxy rotation curves
• Detected via gravitational lensing
• Candidates: WIMPs, axions

Planck 2018:
Ωₘ ≈ 0.315 | ΩΛ ≈ 0.685
        """

    elif "time" in q:
        answer = """
⏱️ **TIME DILATION (GR)**

Formula:
t₀ = t √(1 − 2GM / rc²)

GPS satellites:
• +45 μs/day (GR)
• −7 μs/day (SR)
• Net +38 μs/day correction

Verified experimentally.
        """

    else:
        answer = f"""
🔬 **PHYSICS ANALYSIS**

Retrieved {len(docs)} documents.

Top context:
{context[:1000]}...
        """

    return f"{answer}\n\n📚 **Sources Used**: {len(docs)} physics documents"

# -----------------------------
# GRADIO INTERFACE
# -----------------------------
demo = gr.Interface(
    fn=detailed_physics_app,
    inputs=gr.Textbox(
        label="🔬 Physics Question",
        lines=3,
        placeholder="Ask about string theory, dark energy, time dilation..."
    ),
    outputs=gr.Markdown(label="Detailed Physics Answer"),
    title="🌌 Physics RAG Agent",
    description="Long-form explanations using Retrieval-Augmented Generation",
    examples=[
        ["Explain string theory in detail"],
        ["Dark energy vs dark matter"],
        ["Time dilation GPS correction"],
        ["How do stars form?"]
    ]
)

if __name__ == "__main__":
    demo.launch()
